import { useMemo, useState } from 'react';
import { X } from 'lucide-react';
import {
  CONTENT_TYPE_OPTIONS,
  PLACEMENT_OPTIONS,
  type AdaptivePlacementMode,
  type AuthorableAdaptiveTag,
  type ContentBlockType,
  type LearningContentRecord,
  type PublishStatus,
} from '@/features/courseBuilder/types';
import styles from './ContentBlockForm.module.css';

export type ContentBlockPayload = {
  contentType: ContentBlockType;
  adaptiveTag: AuthorableAdaptiveTag;
  scaffoldLevel: number;
  isEnrichment: boolean;
  status: PublishStatus;
  contentData: Record<string, unknown>;
  /** Optional explicit order — used to anchor emotion content to a baseline block. */
  sequenceOrder?: number;
};

type Props = {
  /** Fixed emotion channel this block belongs to. 'baseline' = normal lesson content. */
  adaptiveTag: AuthorableAdaptiveTag;
  /** Content type the form starts on when creating a new block. */
  defaultContentType?: ContentBlockType;
  /** Existing block when editing; null when creating. */
  initial?: LearningContentRecord | null;
  /** Status applied to newly created blocks (mirrors the lesson status). */
  defaultStatus?: PublishStatus;
  title?: string;
  onCancel: () => void;
  onSubmit: (payload: ContentBlockPayload) => Promise<void> | void;
};

function asText(value: unknown) {
  return typeof value === 'string' ? value.trim() : '';
}

function initialBody(data: Record<string, unknown> | undefined, type: ContentBlockType) {
  if (!data) return '';
  if (type === 'TEXT') return asText(data.text);
  if (type === 'ASSESSMENT') return '';
  return asText(data.caption) || asText(data.transcript);
}

export default function ContentBlockForm({
  adaptiveTag,
  defaultContentType = 'TEXT',
  initial = null,
  defaultStatus = 'draft',
  title,
  onCancel,
  onSubmit,
}: Props) {
  const isEmotion = adaptiveTag !== 'baseline';
  const startType = (initial?.contentType ?? defaultContentType) as ContentBlockType;

  const [contentType, setContentType] = useState<ContentBlockType>(startType);
  const [heading, setHeading] = useState(() => asText(initial?.contentData.title));
  const [body, setBody] = useState(() => initialBody(initial?.contentData, startType));
  const [url, setUrl] = useState(
    () => asText(initial?.contentData.url) || asText(initial?.contentData.resourceUrl),
  );
  const [renderMode, setRenderMode] = useState<'image' | 'document'>(
    () => (asText(initial?.contentData.renderMode) === 'document' ? 'document' : 'image'),
  );
  const [question, setQuestion] = useState(() => asText(initial?.contentData.question));
  const [optionsText, setOptionsText] = useState(() =>
    Array.isArray(initial?.contentData.options)
      ? (initial!.contentData.options as unknown[]).filter((v): v is string => typeof v === 'string').join('\n')
      : '',
  );
  const [prompt, setPrompt] = useState(() => asText(initial?.contentData.prompt));
  const [hint, setHint] = useState(() => asText(initial?.contentData.hint));
  const [taskContextKey, setTaskContextKey] = useState(() => asText(initial?.contentData.taskContextKey));
  const [note, setNote] = useState(() => asText(initial?.contentData.note));
  const [scaffoldLevel, setScaffoldLevel] = useState<number>(initial?.scaffoldLevel ?? 3);
  const [isEnrichment, setIsEnrichment] = useState<boolean>(initial?.isEnrichment ?? adaptiveTag === 'high_engagement');
  const [placementMode, setPlacementMode] = useState<Exclude<AdaptivePlacementMode, 'baseline'>>(() => {
    const stored = asText(initial?.contentData.journeyPlacementMode) || asText(initial?.contentData.placementMode);
    return stored === 'before' || stored === 'instead' ? stored : 'after';
  });
  const [anchorOrder, setAnchorOrder] = useState<string>(() =>
    initial && isEmotion ? String(initial.sequenceOrder ?? '') : '',
  );

  const modalTitle = title ?? (initial ? 'تعديل المكوّن' : 'إضافة مكوّن');

  const canSubmit = useMemo(() => {
    if (contentType === 'ASSESSMENT') return Boolean(question.trim() || heading.trim());
    if (contentType === 'VISUAL' || contentType === 'VIDEO') return Boolean(url.trim() || heading.trim());
    return Boolean(heading.trim() || body.trim());
  }, [body, contentType, heading, question, url]);

  function buildContentData(): Record<string, unknown> {
    const data: Record<string, unknown> = { ...(initial?.contentData ?? {}) };
    data.title = heading.trim();
    data.autoGenerated = false;

    // Reset the keys this form manages so switching type never leaves stale data.
    for (const key of ['text', 'caption', 'transcript', 'url', 'resourceUrl', 'renderMode', 'question', 'options', 'prompt', 'hint', 'taskContextKey']) {
      delete data[key];
    }

    if (contentType === 'TEXT') {
      if (body.trim()) data.text = body.trim();
    } else if (contentType === 'VISUAL') {
      if (url.trim()) {
        data.url = url.trim();
        data.resourceUrl = url.trim();
      }
      if (body.trim()) data.caption = body.trim();
      data.renderMode = renderMode;
    } else if (contentType === 'VIDEO') {
      if (url.trim()) {
        data.url = url.trim();
        data.resourceUrl = url.trim();
      }
      if (body.trim()) data.caption = body.trim();
    } else if (contentType === 'ASSESSMENT') {
      data.question = question.trim() || heading.trim();
      const options = optionsText
        .split(/\r?\n/)
        .map((item) => item.trim())
        .filter(Boolean);
      if (options.length) data.options = options;
      if (prompt.trim()) data.prompt = prompt.trim();
      if (hint.trim()) data.hint = hint.trim();
      if (taskContextKey.trim()) data.taskContextKey = taskContextKey.trim();
    }

    if (note.trim()) data.note = note.trim();
    else delete data.note;

    data.journeyPlacementMode = isEmotion ? placementMode : 'baseline';
    return data;
  }

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    if (!canSubmit) return;

    const parsedAnchor = anchorOrder.trim() ? Number(anchorOrder.trim()) : undefined;
    const payload: ContentBlockPayload = {
      contentType,
      adaptiveTag,
      scaffoldLevel,
      isEnrichment,
      status: initial?.status ?? defaultStatus,
      contentData: buildContentData(),
      sequenceOrder: isEmotion && parsedAnchor && !Number.isNaN(parsedAnchor) ? parsedAnchor : undefined,
    };
    await onSubmit(payload);
  }

  return (
    <div className="modal-overlay" onMouseDown={(e) => e.target === e.currentTarget && onCancel()}>
      <form className={`card ${styles.modalCard}`} onSubmit={handleSubmit}>
        <div className={styles.modalHead}>
          <strong>{modalTitle}</strong>
          <button type="button" className="btn btn-ghost btn-sm" onClick={onCancel} aria-label="إغلاق">
            <X size={16} />
          </button>
        </div>

        <div className={styles.formBody}>
          <label className={styles.field}>
            <span>نوع المكوّن</span>
            <select
              className="input"
              value={contentType}
              onChange={(e) => setContentType(e.target.value as ContentBlockType)}
            >
              {CONTENT_TYPE_OPTIONS.map((option) => (
                <option key={option.value} value={option.value}>
                  {option.label}
                </option>
              ))}
            </select>
          </label>

          <label className={styles.field}>
            <span>العنوان</span>
            <input className="input" value={heading} onChange={(e) => setHeading(e.target.value)} placeholder="عنوان المكوّن" />
          </label>

          {contentType === 'TEXT' ? (
            <label className={styles.field}>
              <span>النص / الشرح</span>
              <textarea className="input" rows={5} value={body} onChange={(e) => setBody(e.target.value)} />
            </label>
          ) : null}

          {contentType === 'VISUAL' || contentType === 'VIDEO' ? (
            <>
              <label className={styles.field}>
                <span>{contentType === 'VIDEO' ? 'رابط الفيديو (YouTube / mp4 …)' : 'رابط الصورة / الملف'}</span>
                <input className="input" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://..." />
              </label>
              {contentType === 'VISUAL' ? (
                <label className={styles.field}>
                  <span>طريقة العرض</span>
                  <select className="input" value={renderMode} onChange={(e) => setRenderMode(e.target.value as 'image' | 'document')}>
                    <option value="image">صورة</option>
                    <option value="document">مستند / PDF</option>
                  </select>
                </label>
              ) : null}
              <label className={styles.field}>
                <span>وصف / تعليق (اختياري)</span>
                <textarea className="input" rows={2} value={body} onChange={(e) => setBody(e.target.value)} />
              </label>
            </>
          ) : null}

          {contentType === 'ASSESSMENT' ? (
            <>
              <label className={styles.field}>
                <span>نص السؤال / المهمة</span>
                <textarea className="input" rows={2} value={question} onChange={(e) => setQuestion(e.target.value)} />
              </label>
              <label className={styles.field}>
                <span>خيارات الإجابة (خيار في كل سطر — اتركه فارغًا لسؤال مفتوح)</span>
                <textarea className="input" rows={4} value={optionsText} onChange={(e) => setOptionsText(e.target.value)} />
              </label>
              <label className={styles.field}>
                <span>تلميح مساعد (اختياري)</span>
                <input className="input" value={hint} onChange={(e) => setHint(e.target.value)} />
              </label>
              <label className={styles.field}>
                <span>مفتاح سياق المهمة (اختياري)</span>
                <input className="input" value={taskContextKey} onChange={(e) => setTaskContextKey(e.target.value)} placeholder="scope_analysis, wbs …" />
              </label>
            </>
          ) : null}

          <label className={styles.field}>
            <span>ملاحظة إرشادية (اختياري)</span>
            <input className="input" value={note} onChange={(e) => setNote(e.target.value)} />
          </label>

          <div className={styles.inlineFields}>
            <label className={styles.field}>
              <span>مستوى الدعم (1-5)</span>
              <input
                className="input"
                type="number"
                min={1}
                max={5}
                value={scaffoldLevel}
                onChange={(e) => setScaffoldLevel(Number(e.target.value) || 3)}
              />
            </label>
            <label className={`${styles.field} ${styles.checkboxField}`}>
              <input type="checkbox" checked={isEnrichment} onChange={(e) => setIsEnrichment(e.target.checked)} />
              <span>عنصر إثرائي اختياري</span>
            </label>
          </div>

          {isEmotion ? (
            <div className={styles.inlineFields}>
              <label className={styles.field}>
                <span>موضع الظهور</span>
                <select
                  className="input"
                  value={placementMode}
                  onChange={(e) => setPlacementMode(e.target.value as Exclude<AdaptivePlacementMode, 'baseline'>)}
                >
                  {PLACEMENT_OPTIONS.map((option) => (
                    <option key={option.value} value={option.value}>
                      {option.label}
                    </option>
                  ))}
                </select>
              </label>
              <label className={styles.field}>
                <span>يرتبط بترتيب العنصر الأساسي (اختياري)</span>
                <input
                  className="input"
                  type="number"
                  min={1}
                  value={anchorOrder}
                  onChange={(e) => setAnchorOrder(e.target.value)}
                  placeholder="رقم العنصر الأساسي المستهدف"
                />
              </label>
            </div>
          ) : null}
        </div>

        <div className={styles.modalActions}>
          <button type="button" className="btn btn-secondary" onClick={onCancel}>
            إلغاء
          </button>
          <button type="submit" className="btn btn-primary" disabled={!canSubmit}>
            حفظ المكوّن
          </button>
        </div>
      </form>
    </div>
  );
}
